[system]
host = "0.0.0.0"
port = 8080
debug = true
log = "logs/sys.log"

[mysql]
host = "127.0.0.1"
port = "3306"
user = "root"
password = "123456"
database = "oauth"

[redis]
host = ":6379"
password = ""
database = 15

[jwt]
key = "0P0ifhzLLoFZkEZzVm1d1w"